// Build the embedded workbench into dist/ (committed; `cargo build` never runs Node).
//
//   node build.mjs            write dist/
//   node build.mjs --check    rebuild in memory and fail when dist/ differs
//
// Outputs: app.js and app.css (minified, with .gz twins served to gzip clients),
// gzip copies of the vendored marked/DOMPurify modules, the static shell files,
// and manifest.json (sizes, SHA-256, tool versions and a digest of the sources,
// which scripts/test_web_dist.py checks without Node).
import { createHash } from "node:crypto";
import { mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { gunzipSync, gzipSync } from "node:zlib";
import * as esbuild from "esbuild";

const here = dirname(fileURLToPath(import.meta.url));
const vendor = join(here, "../../../../../vendor/web");
const dist = join(here, "dist");
const check = process.argv.includes("--check");
const sha256 = (bytes) => createHash("sha256").update(bytes).digest("hex");
// Browsers this targets: everything with color-mix(), :has() and container queries.
const target = ["es2022", "chrome111", "edge111", "firefox121", "safari16.4"];

/** Deterministic gzip: zlib level 9, zero mtime, "unknown" OS byte. */
function gzip(bytes) {
  const out = gzipSync(bytes, { level: 9 });
  out[9] = 0xff;
  return out;
}

/** Files whose content decides the build output, in a fixed order. */
export function sourceFiles() {
  const files = [];
  const walk = (directory) => {
    for (const name of readdirSync(directory).sort()) {
      const path = join(directory, name);
      if (statSync(path).isDirectory()) walk(path);
      else if (!name.endsWith(".test.ts")) files.push(path);
    }
  };
  walk(join(here, "src"));
  walk(join(here, "public"));
  for (const name of ["build.mjs", "package-lock.json", "tsconfig.json"]) files.push(join(here, name));
  return files;
}

/** SHA-256 over each source's relative path and bytes (scripts/test_web_dist.py repeats this). */
export function sourceDigest() {
  const hash = createHash("sha256");
  for (const path of sourceFiles()) {
    hash.update(relative(here, path).split("\\").join("/"));
    hash.update("\0");
    hash.update(readFileSync(path));
    hash.update("\0");
  }
  return hash.digest("hex");
}

async function bundle(entry, extra = {}) {
  const result = await esbuild.build({
    entryPoints: [join(here, entry)],
    bundle: true,
    write: false,
    minify: true,
    target,
    charset: "utf8",
    legalComments: "none",
    logLevel: "warning",
    external: ["/ui/*"],
    outdir: dist,
    ...extra,
  });
  const [file] = result.outputFiles;
  return Buffer.from(file.contents);
}

async function build() {
  const outputs = new Map();
  outputs.set("app.js", await bundle("src/main.tsx", { format: "esm", jsx: "automatic", jsxImportSource: "preact" }));
  outputs.set("app.css", await bundle("src/styles/app.css", { loader: { ".css": "css" } }));
  for (const name of ["index.html", "boot.js", "logo.svg"]) outputs.set(name, readFileSync(join(here, "public", name)));
  for (const name of ["app.js", "app.css"]) outputs.set(`${name}.gz`, gzip(outputs.get(name)));
  for (const name of ["marked.js", "purify.js"]) outputs.set(`${name}.gz`, gzip(readFileSync(join(vendor, name))));
  const version = (name) => JSON.parse(readFileSync(join(here, "node_modules", name, "package.json"), "utf8")).version;
  const manifest = {
    note: "Generated by build.mjs; do not edit.",
    source_digest: sourceDigest(),
    tools: { esbuild: version("esbuild"), preact: version("preact"), typescript: version("typescript") },
    vendor: Object.fromEntries(["marked.js", "purify.js"].map((name) => [name, sha256(readFileSync(join(vendor, name)))])),
    files: Object.fromEntries(
      [...outputs.keys()].sort().map((name) => [name, { bytes: outputs.get(name).length, sha256: sha256(outputs.get(name)) }]),
    ),
  };
  outputs.set("manifest.json", Buffer.from(`${JSON.stringify(manifest, null, 2)}\n`));
  return outputs;
}

const outputs = await build();
if (check) {
  const stale = [];
  for (const [name, bytes] of outputs) {
    let current;
    try {
      current = readFileSync(join(dist, name));
    } catch {
      stale.push(`${name} (missing)`);
      continue;
    }
    // Compressed twins are compared by content: zlib builds may encode differently.
    const same = name.endsWith(".gz") ? gunzipSync(current).equals(gunzipSync(bytes)) : current.equals(bytes);
    if (!same && name !== "manifest.json") stale.push(name);
  }
  const manifest = JSON.parse(readFileSync(join(dist, "manifest.json"), "utf8"));
  if (manifest.source_digest !== sourceDigest()) stale.push("manifest.json (source digest)");
  if (stale.length) {
    console.error(`dist/ is stale; run \`node build.mjs\`:\n  ${stale.join("\n  ")}`);
    process.exit(1);
  }
  console.log(`dist/ matches the sources (${outputs.size} files)`);
} else {
  mkdirSync(dist, { recursive: true });
  for (const [name, bytes] of outputs) writeFileSync(join(dist, name), bytes);
  const size = (name) => `${name} ${outputs.get(name).length} B`;
  console.log(["app.js", "app.js.gz", "app.css", "app.css.gz", "marked.js.gz", "purify.js.gz"].map(size).join(" · "));
}
