[package]
name = "heifer-hevc-enc"
description = "Pure-Rust HEVC (H.265) intra encoder for still images"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
thiserror.workspace = true
heifer-hevc-dec.workspace = true


[lints]
workspace = true
