[package]
name = "heifer-isobmff"
description = "ISOBMFF / HEIF container reading and writing (ISO/IEC 14496-12, 23008-12)"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
thiserror.workspace = true


[lints]
workspace = true
